parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Infrastructure/Mapping/Doctrine'
            - '../src/Infrastructure/Route/'

    App\Action\:
        resource: '../src/Action/'
        tags: ['controller.service_arguments']

    Knp\Component\Pager\Paginator: ~

    App\Infrastructure\Paginator\AppPaginator:
        decorates: Knp\Component\Pager\Paginator

    App\Repository\BlogPostRepository: '@App\Infrastructure\Repository\Doctrine\DoctrineBlogPostRepository'

#    Only if using PSR-7 bridge and ServerRequestInterface
    Nyholm\Psr7\Factory\Psr17Factory: ~
    Psr\Http\Message\ServerRequestFactoryInterface: '@Nyholm\Psr7\Factory\Psr17Factory'

    Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory: ~
    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'
